//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<emp> emp { get; set; }
        public virtual DbSet<gender> gender { get; set; }
        public virtual DbSet<personality> personality { get; set; }
        public virtual DbSet<reports> reports { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<tasks> tasks { get; set; }
    }
}
